OBJS = IoOpen.o IoWriter.o IoReader.o IoPopen.o IoReadline.o \
       UsingIoOpen.o UsingIoWriter.o UsingIoReader.o UsingIoPopen.o \
       IoEach.o IoEachWithIndex.o UsingIoEach.o UsingIoEachWithIndex.o \
       IoBinaryWriter.o IoBinaryReader.o UsingIoBinaryWriter.o \
       UsingIoBinaryReader.o IoReadByte.o

DOBJS = IoOpen.debug IoWriter.debug IoReader.debug IoPopen.debug \
        IoReadline.debug UsingIoOpen.debug UsingIoWriter.debug \
        UsingIoReader.debug UsingIoPopen.debug IoEach.debug \
        IoEachWithIndex.debug UsingIoEach.debug \
        UsingIoEachWithIndex.debug IoBinaryWriter.debug \
        IoBinaryReader.debug UsingIoBinaryWriter.debug \
        UsingIoBinaryReader.debug IoReadByte.debug


include Makefile.in
