OBJS = IoOpen.o IoWriter.o IoReader.o IoPopen.o IoReadline.o \
       UsingIoOpen.o UsingIoWriter.o UsingIoReader.o UsingIoPopen.o \
       IoEach.o IoEachWithIndex.o UsingIoEach.o UsingIoEachWithIndex.o

DOBJS = IoOpen.debug IoWriter.debug IoReader.debug IoPopen.debug \
        IoReadline.debug UsingIoOpen.debug UsingIoWriter.debug \
        UsingIoReader.debug UsingIoPopen.debug IoEach.debug \
        IoEachWithIndex.debug UsingIoEach.debug \
        UsingIoEachWithIndex.debug

include Makefile.in
